---
- name: Create Table_of_Contents
  hosts: localhost
  gather_facts: no

  vars_prompt:
    - name: folder_path
      prompt: "Enter the path of the folder to be run against"
      private: no

  tasks:
    - name: Install required packages
      become: yes
      dnf:
        name: tree
        state: present

    - name: Get the base directory name
      command: basename "{{ folder_path }}"
      register: base_dir_name

    - name: Run tree command to get directory structure
      command: tree -H . -L 2
      register: tree_output
      args:
        chdir: "{{ folder_path }}"

    - name: Write tree output to markdown file
      copy:
        dest: "/tmp/{{ base_dir_name.stdout }}_Table_of_Contents.md"
        content: |
          # Table_of_Contents_of_{{ base_dir_name.stdout }}
          
          {{ tree_output.stdout }}

    - name: Move the markdown file to the base directory
      command: mv /tmp/{{ base_dir_name.stdout }}_Table_of_Contents.md "{{ folder_path }}/{{ base_dir_name.stdout }}_Table_of_Contents.md"

